<!DOCTYPE html><html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" lang="en"><head><title></title><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml><![endif]--><style>
*{box-sizing:border-box}body{margin:0;padding:0}a[x-apple-data-detectors]{color:inherit!important;text-decoration:inherit!important}#MessageViewBody a{color:inherit;text-decoration:none}p{line-height:inherit}.desktop_hide,.desktop_hide table{mso-hide:all;display:none;max-height:0;overflow:hidden}.menu_block.desktop_hide .menu-links span{mso-hide:all}@media (max-width:700px){.desktop_hide table.icons-inner{display:inline-block!important}.icons-inner{text-align:center}.icons-inner td{margin:0 auto}.fullMobileWidth,.row-content{width:100%!important}.menu-checkbox[type=checkbox]~.menu-links{display:none!important;padding:5px 0}.menu-checkbox[type=checkbox]:checked~.menu-trigger .menu-open{display:none!important}.menu-checkbox[type=checkbox]:checked~.menu-links,.menu-checkbox[type=checkbox]~.menu-trigger{display:block!important;max-width:none!important;max-height:none!important;font-size:inherit!important}.menu-checkbox[type=checkbox]~.menu-links>a,.menu-checkbox[type=checkbox]~.menu-links>span.label{display:block!important;text-align:center}.menu-checkbox[type=checkbox]:checked~.menu-trigger .menu-close{display:block!important}.mobile_hide{display:none}.stack .column{width:100%;display:block}.mobile_hide{min-height:0;max-height:0;max-width:0;overflow:hidden;font-size:0}.desktop_hide,.desktop_hide table{display:table!important;max-height:none!important}}#menu111:checked~.menu-links{background-color:#1e2f40!important}#menu111:checked~.menu-links a,#menu111:checked~.menu-links span{color:#fff!important}
</style></head><body style="background-color:#133c55;margin:0;padding:0;-webkit-text-size-adjust:none;text-size-adjust:none"><table class="nl-container" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#133c55"><tbody><tr><td><table class="row row-1" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;background-color:#b4ebfc"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:680px" width="680"><tbody><tr><td class="column column-1" width="100%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:5px;padding-bottom:5px;border-top:0;border-right:0;border-bottom:0;border-left:0"><div class="spacer_block" style="height:20px;line-height:20px;font-size:1px">&#8202;</div></td></tr></tbody></table></td></tr></tbody></table><table class="row row-2" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;background-color:#b4ebfc"><tbody><tr><td><table class="row-content" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:680px" width="680"><tbody><tr><td class="column column-1" width="41.666666666666664%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table
 class="icons_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="vertical-align:middle;color:#000;text-align:left;font-family:inherit;font-size:14px;padding-top:5px;padding-bottom:5px"><table class="alignment" cellpadding="0" cellspacing="0" role="presentation" align="left" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td 
style="vertical-align:middle;text-align:center;padding-top:5px;padding-bottom:5px;padding-left:5px;padding-right:5px"><img class="icon" src="https://d1oco4z2z1fhwp.cloudfront.net/templates/default/4646/Logo_1.png" alt height="32" width="125" align="center" style="display:block;height:auto;margin:0 auto;border:0"></td></tr></table></td></tr></table></td><td class="column column-2" width="58.333333333333336%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="menu_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="text-align:right;color:#1e2f40;padding-right:15px;font-family:inherit;font-size:16px;padding-top:5px;padding-bottom:5px"><table width="100%" cellpadding="0" 
cellspacing="0" border="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="alignment" style="text-align:right;font-size:0"><!--[if !mso]><!--><input class="menu-checkbox" id="menu111" type="checkbox" style="display:none!important;max-height:0;visibility:hidden"><!--<![endif]--><div class="menu-trigger" style="display:none;max-height:0;max-width:0;font-size:0;overflow:hidden"><label class="menu-label" for="menu111" 
style="height:36px;width:36px;display:inline-block;cursor:pointer;mso-hide:all;user-select:none;align:right;text-align:center;color:#fff;text-decoration:none;background-color:#1e2f40;border-radius:0"><span class="menu-open" style="mso-hide:all;font-size:26px;line-height:36px;">☰</span><span class="menu-close" style="display:none;mso-hide:all;font-size:26px;line-height:36px;">✕</span></label></div><div class="menu-links"><!--[if mso]>
<table role="presentation" border="0" cellpadding="0" cellspacing="0" align="center" style="">
<tr>
<td style="padding-top:10px;padding-right:10px;padding-bottom:10px;padding-left:10px">
<![endif]--><a href="www.example.com" style="padding-top:10px;padding-bottom:10px;padding-left:10px;padding-right:10px;display:inline-block;color:#1e2f40;font-family:Arial, Helvetica Neue, Helvetica, sans-serif;font-size:16px;text-decoration:none;letter-spacing:normal;">OUR WORK</a><!--[if mso]></td><td style="padding-top:10px;padding-right:10px;padding-bottom:10px;padding-left:10px"><![endif]-->
<a href="www.example.com" style="padding-top:10px;padding-bottom:10px;padding-left:10px;padding-right:10px;display:inline-block;color:#1e2f40;font-family:Arial, Helvetica Neue, Helvetica, sans-serif;font-size:16px;text-decoration:none;letter-spacing:normal;">WILDLIFE</a><!--[if mso]></td><td style="padding-top:10px;padding-right:10px;padding-bottom:10px;padding-left:10px"><![endif]-->
<a href="www.example.com" style="padding-top:10px;padding-bottom:10px;padding-left:10px;padding-right:10px;display:inline-block;color:#1e2f40;font-family:Arial, Helvetica Neue, Helvetica, sans-serif;font-size:16px;text-decoration:none;letter-spacing:normal;">PLACES</a><!--[if mso]></td><td style="padding-top:10px;padding-right:10px;padding-bottom:10px;padding-left:10px"><![endif]-->
<a href="www.example.com" style="padding-top:10px;padding-bottom:10px;padding-left:10px;padding-right:10px;display:inline-block;color:#1e2f40;font-family:Arial, Helvetica Neue, Helvetica, sans-serif;font-size:16px;text-decoration:none;letter-spacing:normal;">PEOPLE</a><!--[if mso]></td></tr></table><![endif]--></div></td></tr></table></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-3" align="center" width="100%" border="0" 
cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#b4ebfc"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:680px" width="680"><tbody><tr><td class="column column-1" width="100%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:5px;padding-bottom:5px;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="heading_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;text-align:center;padding-top:65px;padding-right:10px;padding-bottom:15px;padding-left:10px"><h1 
style="margin:0;color:#272727;font-size:48px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;line-height:120%;text-align:center;direction:ltr;font-weight:400;letter-spacing:normal;margin-top:0;margin-bottom:0"><strong>Global Warming {{$data}}</strong></h1></td></tr></table><table class="text_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" 
style="padding-bottom:15px;padding-left:10px;padding-right:10px;padding-top:10px"><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" style="font-size:12px;mso-line-height-alt:24px;color:#5f5f5f;line-height:2;font-family:Arial,Helvetica Neue,Helvetica,sans-serif"><p style="margin:0;font-size:14px;text-align:center;mso-line-height-alt:32px">
<span style="font-size:16px;">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes</span></p></div></div></td></tr></table><table class="button_block block-4" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad"><div class="alignment" align="center">
<!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="www.example.com" style="height:44px;width:149px;v-text-anchor:middle;" arcsize="10%" strokeweight="0.75pt" strokecolor="#133C55" fillcolor="#133c55"><w:anchorlock/><v:textbox inset="0px,0px,0px,0px"><center style="color:#ffffff; font-family:Arial, sans-serif; font-size:16px"><![endif]-->
<a href="www.example.com" target="_blank" style="text-decoration:none;display:inline-block;color:#ffffff;background-color:#133c55;border-radius:4px;width:auto;border-top:1px solid #133C55;font-weight:undefined;border-right:1px solid #133C55;border-bottom:1px solid #133C55;border-left:1px solid #133C55;padding-top:5px;padding-bottom:5px;font-family:Arial, Helvetica Neue, Helvetica, sans-serif;text-align:center;mso-border-alt:none;word-break:keep-all;"><span style="padding-left:20px;padding-right:20px;font-size:16px;display:inline-block;letter-spacing:normal;"><span style="font-size: 16px; line-height: 2; word-break: break-word; mso-line-height-alt: 32px;">LEARN MORE</span></span></a>
<!--[if mso]></center></v:textbox></v:roundrect><![endif]--></div></td></tr></table><table class="image_block block-6" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0;padding-top:50px;padding-bottom:55px"><div class="alignment" align="center" style="line-height:10px"><img class="fullMobileWidth" 
src="https://d1oco4z2z1fhwp.cloudfront.net/templates/default/4646/Polar_bear.png" style="display:block;height:auto;border:0;width:374px;max-width:100%" width="374" alt="Polar bear sitting on tiny ice" title="Polar bear sitting on tiny ice"></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-4" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;background-position:center top"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:680px" width="680"><tbody><tr><td class="column column-1" width="100%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:5px;padding-bottom:5px;border-top:0;border-right:0;border-bottom:0;border-left:0"><div class="spacer_block" style="height:70px;line-height:70px;font-size:1px">&#8202;</div></td></tr></tbody></table></td></tr></tbody></table><table class="row row-5" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0">
<tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:680px" width="680"><tbody><tr><td class="column column-1" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="image_block block-2" width="100%" border="0" cellpadding="0" 
cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;padding-top:15px;padding-right:10px;padding-bottom:15px;padding-left:10px"><div class="alignment" align="center" style="line-height:10px"><img class="fullMobileWidth" src="https://d1oco4z2z1fhwp.cloudfront.net/templates/default/4646/activist_environment.png" style="display:block;height:auto;border:0;width:320px;max-width:100%" width="320" alt="Activist" title="Activist"></div>
</td></tr></table></td><td class="column column-2" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="heading_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;text-align:center;padding-left:10px;padding-top:55px"><h3 
style="margin:0;color:#edddd4;font-size:17px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;line-height:120%;text-align:left;direction:ltr;font-weight:400;letter-spacing:normal;margin-top:0;margin-bottom:0"><strong>Jessica James</strong></h3></td></tr></table><table class="heading_block block-4" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" 
style="width:100%;text-align:center;padding-top:15px;padding-left:10px"><h2 style="margin:0;color:#fff;font-size:24px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;line-height:150%;text-align:left;direction:ltr;font-weight:400;letter-spacing:normal;margin-top:0;margin-bottom:0"><strong>The Climate Is Changing. But What Does This Mean</strong></h2></td></tr></table><table class="text_block block-5" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-bottom:15px;padding-left:10px;padding-right:10px;padding-top:10px"><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" style="font-size:12px;mso-line-height-alt:24px;color:#d3d3d3;line-height:2;font-family:Arial,Helvetica Neue,Helvetica,sans-serif"><p style="margin:0;font-size:14px;text-align:left">
<span style>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes</span></p></div></div></td></tr></table><table class="button_block block-6" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="text-align:left;padding-top:10px;padding-right:10px;padding-bottom:15px;padding-left:10px"><div 
class="alignment" align="left"><!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="www.example.com" style="height:44px;width:151px;v-text-anchor:middle;" arcsize="10%" strokeweight="0.75pt" strokecolor="#133C55" fillcolor="#b4ebfc"><w:anchorlock/><v:textbox inset="0px,0px,0px,0px"><center style="color:#133c55; font-family:Arial, sans-serif; font-size:16px"><![endif]-->
<a href="www.example.com" target="_blank" style="text-decoration:none;display:inline-block;color:#133c55;background-color:#b4ebfc;border-radius:4px;width:auto;border-top:1px solid #133C55;font-weight:undefined;border-right:1px solid #133C55;border-bottom:1px solid #133C55;border-left:1px solid #133C55;padding-top:5px;padding-bottom:5px;font-family:Arial, Helvetica Neue, Helvetica, sans-serif;text-align:center;mso-border-alt:none;word-break:keep-all;"><span style="padding-left:20px;padding-right:20px;font-size:16px;display:inline-block;letter-spacing:normal;"><span style="font-size: 16px; line-height: 2; word-break: break-word; mso-line-height-alt: 32px;"><strong>TAKE ACTION</strong></span></span></a>
<!--[if mso]></center></v:textbox></v:roundrect><![endif]--></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-6" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:680px" 
width="680"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:5px;padding-bottom:5px;border-top:0;border-right:0;border-bottom:0;border-left:0"><div class="spacer_block" style="height:60px;line-height:60px;font-size:1px">&#8202;</div></td></tr></tbody></table></td></tr></tbody></table><table class="row row-7" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" 
role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#0d2c3f"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:680px" width="680"><tbody><tr><td class="column column-1" width="100%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:5px;padding-bottom:5px;border-top:0;border-right:0;border-bottom:0;border-left:0"><div class="spacer_block" style="height:35px;line-height:35px;font-size:1px">&#8202;</div></td></tr></tbody></table></td></tr></tbody></table><table class="row row-8" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;background-color:#0d2c3f"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:680px" width="680"><tbody><tr><td class="column column-1" width="75%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table 
class="heading_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;text-align:center;padding-top:20px;padding-left:10px;padding-bottom:5px"><h2 style="margin:0;color:#fff;font-size:24px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;line-height:150%;text-align:left;direction:ltr;font-weight:400;letter-spacing:normal;margin-top:0;margin-bottom:0">
<strong>The Climate Is Changing. But What Does This Mean</strong></h2></td></tr></table></td><td class="column column-2" width="25%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><div class="spacer_block" style="height:30px;line-height:5px;font-size:1px">&#8202;</div></td></tr></tbody></table></td></tr></tbody></table><table class="row row-9" align="center" width="100%" border="0" 
cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#0d2c3f"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:680px" width="680"><tbody><tr><td class="column column-1" width="100%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:5px;padding-bottom:5px;border-top:0;border-right:0;border-bottom:0;border-left:0"><div class="spacer_block" style="height:20px;line-height:20px;font-size:1px">&#8202;</div></td></tr></tbody></table></td></tr></tbody></table><table class="row row-10" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;background-color:#0d2c3f"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:680px" width="680"><tbody><tr><td class="column column-1" width="33.333333333333336%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0">
<table class="heading_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;text-align:center;padding-top:20px;padding-left:10px"><h2 style="margin:0;color:#fff;font-size:37px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;line-height:150%;text-align:left;direction:ltr;font-weight:400;letter-spacing:normal;margin-top:0;margin-bottom:0"><strong>45+</strong></h2></td>
</tr></table><table class="text_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-bottom:20px;padding-left:10px;padding-right:10px;padding-top:10px"><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" style="font-size:12px;mso-line-height-alt:24px;color:#fff;line-height:2;font-family:Arial,Helvetica Neue,Helvetica,sans-serif"><p 
style="margin:0;font-size:14px;text-align:left;mso-line-height-alt:32px"><span style="font-size:16px;">Contributions</span></p></div></div></td></tr></table></td><td class="column column-2" width="33.333333333333336%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="heading_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;text-align:center;padding-top:20px;padding-left:10px"><h2 style="margin:0;color:#fff;font-size:37px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;line-height:150%;text-align:left;direction:ltr;font-weight:400;letter-spacing:normal;margin-top:0;margin-bottom:0"><strong>23</strong></h2></td></tr></table><table class="text_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" 
role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-bottom:20px;padding-left:10px;padding-right:10px;padding-top:10px"><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" style="font-size:12px;mso-line-height-alt:24px;color:#fff;line-height:2;font-family:Arial,Helvetica Neue,Helvetica,sans-serif"><p style="margin:0;font-size:14px;text-align:left;mso-line-height-alt:32px">
<span style="font-size:16px;">Foundations</span></p></div></div></td></tr></table></td><td class="column column-3" width="33.333333333333336%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="heading_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" 
style="width:100%;text-align:center;padding-top:20px;padding-left:10px"><h2 style="margin:0;color:#fff;font-size:37px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;line-height:150%;text-align:left;direction:ltr;font-weight:400;letter-spacing:normal;margin-top:0;margin-bottom:0"><strong>145</strong></h2></td></tr></table><table class="text_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-bottom:20px;padding-left:10px;padding-right:10px;padding-top:10px"><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" style="font-size:12px;mso-line-height-alt:24px;color:#fff;line-height:2;font-family:Arial,Helvetica Neue,Helvetica,sans-serif"><p style="margin:0;font-size:14px;mso-line-height-alt:32px"><span style="font-size:16px;">Cases Raised</span></p></div></div></td></tr>
</table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-11" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#0d2c3f"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:680px" width="680"><tbody><tr><td class="column column-1" 
width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:5px;padding-bottom:5px;border-top:0;border-right:0;border-bottom:0;border-left:0"><div class="spacer_block" style="height:35px;line-height:35px;font-size:1px">&#8202;</div></td></tr></tbody></table></td></tr></tbody></table><table class="row row-12" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:680px" width="680"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:5px;padding-bottom:5px;border-top:0;border-right:0;border-bottom:0;border-left:0"><div 
class="spacer_block" style="height:60px;line-height:60px;font-size:1px">&#8202;</div></td></tr></tbody></table></td></tr></tbody></table><table class="row row-13" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:680px" 
width="680"><tbody><tr><td class="column column-1" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="heading_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;text-align:center;padding-left:10px;padding-top:55px"><h3 
style="margin:0;color:#edddd4;font-size:17px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;line-height:120%;text-align:left;direction:ltr;font-weight:400;letter-spacing:normal;margin-top:0;margin-bottom:0"><strong>Climate Change</strong></h3></td></tr></table><table class="heading_block block-4" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" 
style="width:100%;text-align:center;padding-top:15px;padding-left:10px"><h2 style="margin:0;color:#fff;font-size:24px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;line-height:150%;text-align:left;direction:ltr;font-weight:400;letter-spacing:normal;margin-top:0;margin-bottom:0"><strong>How Can We Solve Climate Change</strong></h2></td></tr></table><table class="text_block block-5" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-bottom:15px;padding-left:10px;padding-right:10px;padding-top:10px"><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" style="font-size:12px;mso-line-height-alt:24px;color:#d3d3d3;line-height:2;font-family:Arial,Helvetica Neue,Helvetica,sans-serif"><p style="margin:0;font-size:14px;text-align:left">
<span style>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes</span></p></div></div></td></tr></table><table class="button_block block-6" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="text-align:left;padding-top:10px;padding-right:10px;padding-bottom:15px;padding-left:10px"><div 
class="alignment" align="left"><!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="www.example.com" style="height:44px;width:151px;v-text-anchor:middle;" arcsize="10%" strokeweight="0.75pt" strokecolor="#133C55" fillcolor="#b4ebfc"><w:anchorlock/><v:textbox inset="0px,0px,0px,0px"><center style="color:#133c55; font-family:Arial, sans-serif; font-size:16px"><![endif]-->
<a href="www.example.com" target="_blank" style="text-decoration:none;display:inline-block;color:#133c55;background-color:#b4ebfc;border-radius:4px;width:auto;border-top:1px solid #133C55;font-weight:undefined;border-right:1px solid #133C55;border-bottom:1px solid #133C55;border-left:1px solid #133C55;padding-top:5px;padding-bottom:5px;font-family:Arial, Helvetica Neue, Helvetica, sans-serif;text-align:center;mso-border-alt:none;word-break:keep-all;"><span style="padding-left:20px;padding-right:20px;font-size:16px;display:inline-block;letter-spacing:normal;"><span style="font-size: 16px; line-height: 2; word-break: break-word; mso-line-height-alt: 32px;"><strong>TAKE ACTION</strong></span></span></a>
<!--[if mso]></center></v:textbox></v:roundrect><![endif]--></div></td></tr></table></td><td class="column column-2" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="image_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" 
style="width:100%;padding-top:15px;padding-right:10px;padding-bottom:75px;padding-left:10px"><div class="alignment" align="center" style="line-height:10px"><img class="fullMobileWidth" src="https://d1oco4z2z1fhwp.cloudfront.net/templates/default/4646/pollution.png" style="display:block;height:auto;border:0;width:320px;max-width:100%" width="320" alt="Pollution" title="Pollution"></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-14" align="center" 
width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#0d2c3f;background-position:top center"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:680px" width="680"><tbody><tr><td class="column column-1" width="50%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-left:10px;padding-right:10px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="heading_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;text-align:center;padding-left:10px;padding-top:70px"><h3 
style="margin:0;color:#edddd4;font-size:17px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;line-height:120%;text-align:left;direction:ltr;font-weight:400;letter-spacing:normal;margin-top:0;margin-bottom:0"><strong>Climate Change</strong></h3></td></tr></table><table class="heading_block block-4" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" 
style="width:100%;text-align:center;padding-top:15px;padding-left:10px"><h2 style="margin:0;color:#fff;font-size:24px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;line-height:150%;text-align:left;direction:ltr;font-weight:400;letter-spacing:normal;margin-top:0;margin-bottom:0"><strong>How Can We Solve Climate Change</strong></h2></td></tr></table><table class="text_block block-5" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-bottom:15px;padding-left:10px;padding-right:10px;padding-top:10px"><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" style="font-size:12px;mso-line-height-alt:24px;color:#d3d3d3;line-height:2;font-family:Arial,Helvetica Neue,Helvetica,sans-serif"><p style="margin:0;font-size:14px;text-align:left">
<span style>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes</span></p></div></div></td></tr></table><table class="button_block block-6" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad"><div class="alignment" align="left">
<!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="www.example.com" style="height:44px;width:151px;v-text-anchor:middle;" arcsize="10%" strokeweight="0.75pt" strokecolor="#133C55" fillcolor="#b4ebfc"><w:anchorlock/><v:textbox inset="0px,0px,0px,0px"><center style="color:#133c55; font-family:Arial, sans-serif; font-size:16px"><![endif]-->
<a href="www.example.com" target="_blank" style="text-decoration:none;display:inline-block;color:#133c55;background-color:#b4ebfc;border-radius:4px;width:auto;border-top:1px solid #133C55;font-weight:undefined;border-right:1px solid #133C55;border-bottom:1px solid #133C55;border-left:1px solid #133C55;padding-top:5px;padding-bottom:5px;font-family:Arial, Helvetica Neue, Helvetica, sans-serif;text-align:center;mso-border-alt:none;word-break:keep-all;"><span style="padding-left:20px;padding-right:20px;font-size:16px;display:inline-block;letter-spacing:normal;"><span style="font-size: 16px; line-height: 2; word-break: break-word; mso-line-height-alt: 32px;"><strong>TAKE ACTION</strong></span></span></a>
<!--[if mso]></center></v:textbox></v:roundrect><![endif]--></div></td></tr></table><table class="image_block block-8" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0;padding-top:35px;padding-bottom:10px"><div class="alignment" align="center" style="line-height:10px"><img 
src="https://d1oco4z2z1fhwp.cloudfront.net/templates/default/4646/ocean_pollution.jpg" style="display:block;height:auto;border:0;width:320px;max-width:100%" width="320" alt="Plastic in Ocean" title="Plastic in Ocean"></div></td></tr></table></td><td class="column column-2" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-left:10px;padding-right:10px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table 
class="image_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0;padding-top:110px"><div class="alignment" align="center" style="line-height:10px"><img src="https://d1oco4z2z1fhwp.cloudfront.net/templates/default/4646/Wild_fire.jpg" style="display:block;height:auto;border:0;width:320px;max-width:100%" width="320" alt="Wild fire" 
title="Wild fire"></div></td></tr></table><table class="image_block block-5" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0;padding-top:100px;padding-bottom:10px"><div class="alignment" align="center" style="line-height:10px"><img src="https://d1oco4z2z1fhwp.cloudfront.net/templates/default/4646/plastic_beach.jpg" 
style="display:block;height:auto;border:0;width:320px;max-width:100%" width="320" alt="Garbage on beach" title="Garbage on beach"></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-15" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#0d2c3f"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" 
role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:680px" width="680"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:5px;padding-bottom:5px;border-top:0;border-right:0;border-bottom:0;border-left:0"><div class="spacer_block" style="height:60px;line-height:60px;font-size:1px">&#8202;</div></td></tr></tbody></table></td></tr></tbody></table><table 
class="row row-16" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#0d2c3f"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:680px" width="680"><tbody><tr><td class="column column-1" width="100%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:5px;padding-bottom:5px;border-top:0;border-right:0;border-bottom:0;border-left:0"><div class="spacer_block" style="height:60px;line-height:60px;font-size:1px">&#8202;</div></td></tr></tbody></table></td></tr></tbody></table><table class="row row-17" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;background-color:#030317"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:680px" width="680"><tbody><tr><td class="column column-1" width="100%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:5px;padding-bottom:5px;border-top:0;border-right:0;border-bottom:0;border-left:0"><div class="spacer_block" style="height:60px;line-height:60px;font-size:1px">&#8202;</div></td></tr></tbody></table></td></tr></tbody></table><table class="row row-18" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;background-color:#030317"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:680px" width="680"><tbody><tr><td class="column column-1" width="33.333333333333336%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0">
<table class="heading_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="padding-left:20px;text-align:center;width:100%;padding-top:5px"><h1 style="margin:0;color:#fff;direction:ltr;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;font-size:18px;font-weight:400;line-height:200%;text-align:left;margin-top:0;margin-bottom:0"><strong>About Us</strong></h1></td></tr></table><table 
class="text_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-bottom:15px;padding-left:20px;padding-right:20px;padding-top:10px"><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" style="font-size:12px;mso-line-height-alt:24px;color:#fff;line-height:2;font-family:Arial,Helvetica Neue,Helvetica,sans-serif"><p 
style="margin:0;font-size:14px">Lorem ipsum dolor sit amet, consectetuer adipiscing elit,&nbsp;</p></div></div></td></tr></table></td><td class="column column-2" width="33.333333333333336%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="heading_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="padding-left:20px;text-align:center;width:100%;padding-top:5px"><h1 style="margin:0;color:#fff;direction:ltr;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;font-size:18px;font-weight:400;line-height:200%;text-align:left;margin-top:0;margin-bottom:0"><strong>Links</strong></h1></td></tr></table><table class="text_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-bottom:10px;padding-left:20px;padding-right:20px;padding-top:10px"><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" style="font-size:12px;mso-line-height-alt:14.399999999999999px;color:#a9a9a9;line-height:1.2;font-family:Arial,Helvetica Neue,Helvetica,sans-serif"><p style="margin:0;font-size:14px">
<a href="http://www.example.com" target="_blank" style="text-decoration: none; color: #ffffff;" rel="noopener">Our Work</a></p></div></div></td></tr></table><table class="text_block block-4" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-bottom:10px;padding-left:20px;padding-right:20px;padding-top:10px"><div style="font-family:sans-serif"><div 
class="txtTinyMce-wrapper" style="font-size:12px;mso-line-height-alt:14.399999999999999px;color:#a9a9a9;line-height:1.2;font-family:Arial,Helvetica Neue,Helvetica,sans-serif"><p style="margin:0;font-size:14px"><a href="http://www.example.com" target="_blank" style="text-decoration: none; color: #ffffff;" rel="noopener">People</a></p></div></div></td></tr></table><table class="text_block block-5" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-bottom:10px;padding-left:20px;padding-right:20px;padding-top:10px"><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" style="font-size:12px;mso-line-height-alt:14.399999999999999px;color:#a9a9a9;line-height:1.2;font-family:Arial,Helvetica Neue,Helvetica,sans-serif"><p style="margin:0;font-size:14px">
<a href="http://www.example.com" target="_blank" style="text-decoration: none; color: #ffffff;" rel="noopener">Wildlife</a></p></div></div></td></tr></table><table class="text_block block-6" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-bottom:15px;padding-left:20px;padding-right:20px;padding-top:10px"><div style="font-family:sans-serif"><div 
class="txtTinyMce-wrapper" style="font-size:12px;mso-line-height-alt:14.399999999999999px;color:#a9a9a9;line-height:1.2;font-family:Arial,Helvetica Neue,Helvetica,sans-serif"><p style="margin:0;font-size:14px"><a href="http://www.example.com" target="_blank" style="text-decoration: none; color: #ffffff;" rel="noopener">Unsubscribe</a></p></div></div></td></tr></table></td><td class="column column-3" width="33.333333333333336%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="heading_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="padding-left:20px;text-align:center;width:100%;padding-top:5px"><h1 
style="margin:0;color:#fff;direction:ltr;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;font-size:18px;font-weight:400;line-height:200%;text-align:left;margin-top:0;margin-bottom:0"><strong>Contact</strong></h1></td></tr></table><table class="text_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" 
style="padding-bottom:10px;padding-left:20px;padding-right:20px;padding-top:10px"><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" style="font-size:12px;mso-line-height-alt:14.399999999999999px;color:#a9a9a9;line-height:1.2;font-family:Arial,Helvetica Neue,Helvetica,sans-serif"><p style="margin:0;font-size:14px"><a href="http://www.example.com" target="_blank" style="text-decoration: none; color: #ffffff;" rel="noopener">Info@company.com</a></p></div></div></td>
</tr></table><table class="text_block block-4" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-bottom:10px;padding-left:20px;padding-right:20px;padding-top:10px"><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" 
style="font-size:12px;mso-line-height-alt:14.399999999999999px;color:#a9a9a9;line-height:1.2;font-family:Arial,Helvetica Neue,Helvetica,sans-serif"><p style="margin:0;font-size:14px"><a href="http://www.example.com" target="_blank" style="text-decoration: none; color: #ffffff;" rel="noopener">Help Center</a></p></div></div></td></tr></table><table class="social_block block-5" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="padding-bottom:15px;padding-left:20px;padding-right:10px;padding-top:10px;text-align:left"><div class="alignment" style="text-align:left"><table class="social-table" width="144px" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;display:inline-block"><tr><td style="padding:0 4px 0 0"><a href="https://www.facebook.com/" target="_blank"><img 
src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-only-logo-white/facebook@2x.png" width="32" height="32" alt="Facebook" title="facebook" style="display:block;height:auto;border:0"></a></td><td style="padding:0 4px 0 0"><a href="https://www.twitter.com/" target="_blank"><img src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-only-logo-white/twitter@2x.png" width="32" height="32" alt="Twitter" title="twitter" 
style="display:block;height:auto;border:0"></a></td><td style="padding:0 4px 0 0"><a href="https://www.linkedin.com/" target="_blank"><img src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-only-logo-white/linkedin@2x.png" width="32" height="32" alt="Linkedin" title="linkedin" style="display:block;height:auto;border:0"></a></td><td style="padding:0 4px 0 0"><a href="https://www.instagram.com/" target="_blank"><img 
src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-only-logo-white/instagram@2x.png" width="32" height="32" alt="Instagram" title="instagram" style="display:block;height:auto;border:0"></a></td></tr></table></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-19" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#030317">
<tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:680px" width="680"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:5px;padding-bottom:5px;border-top:0;border-right:0;border-bottom:0;border-left:0"><div class="spacer_block" 
style="height:60px;line-height:60px;font-size:1px">&#8202;</div></td></tr></tbody></table></td></tr></tbody></table><table class="row row-20" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:680px" width="680"><tbody><tr><td
 class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:5px;padding-bottom:5px;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="icons_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" 
style="vertical-align:middle;color:#9d9d9d;font-family:inherit;font-size:15px;padding-bottom:5px;padding-top:5px;text-align:center"><table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="alignment" style="vertical-align:middle;text-align:center">
<!--[if vml]><table align="left" cellpadding="0" cellspacing="0" role="presentation" style="display:inline-block;padding-left:0px;padding-right:0px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;"><![endif]--><!--[if !vml]><!--><table class="icons-inner" style="mso-table-lspace:0;mso-table-rspace:0;display:inline-block;margin-right:-4px;padding-left:0;padding-right:0" cellpadding="0" cellspacing="0" role="presentation"><!--<![endif]--><tr><td 
style="vertical-align:middle;text-align:center;padding-top:5px;padding-bottom:5px;padding-left:5px;padding-right:6px"><a href="https://www.designedwithbee.com/" target="_blank" style="text-decoration: none;"><img class="icon" alt="Designed with BEE" src="https://d15k2d11r6t6rl.cloudfront.net/public/users/Integrators/BeeProAgency/53601_510656/Signature/bee.png" height="32" width="34" align="center" style="display:block;height:auto;margin:0 auto;border:0"></a></td><td 
style="font-family:Arial,Helvetica Neue,Helvetica,sans-serif;font-size:15px;color:#9d9d9d;vertical-align:middle;letter-spacing:undefined;text-align:center"><a href="https://www.designedwithbee.com/" target="_blank" style="color: #9d9d9d; text-decoration: none;">Designed with BEE</a></td></tr></table></td></tr></table></td></tr></table></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><!-- End --></body></html>